/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: { extend: {} },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',
      'caramellatte',
      'abyss',
      'silk',
      // ── App-inspired custom themes ─────────────────────────────────
      {
        'github-dark': {
          'primary':          '#58a6ff',
          'primary-content':  '#0d1117',
          'secondary':        '#388bfd',
          'secondary-content':'#ffffff',
          'accent':           '#3fb950',
          'accent-content':   '#0d1117',
          'neutral':          '#30363d',
          'neutral-content':  '#c9d1d9',
          'base-100':         '#0d1117',
          'base-200':         '#161b22',
          'base-300':         '#21262d',
          'base-content':     '#c9d1d9',
          'info':             '#388bfd',
          'info-content':     '#ffffff',
          'success':          '#3fb950',
          'success-content':  '#0d1117',
          'warning':          '#d29922',
          'warning-content':  '#0d1117',
          'error':            '#f85149',
          'error-content':    '#ffffff',
        },
      },
      {
        'discord': {
          'primary':          '#5865f2',
          'primary-content':  '#ffffff',
          'secondary':        '#4f545c',
          'secondary-content':'#dcddde',
          'accent':           '#57f287',
          'accent-content':   '#051a0b',
          'neutral':          '#4f545c',
          'neutral-content':  '#dcddde',
          'base-100':         '#36393f',
          'base-200':         '#2f3136',
          'base-300':         '#202225',
          'base-content':     '#dcddde',
          'info':             '#5865f2',
          'info-content':     '#ffffff',
          'success':          '#57f287',
          'success-content':  '#051a0b',
          'warning':          '#fee75c',
          'warning-content':  '#1a1a00',
          'error':            '#ed4245',
          'error-content':    '#ffffff',
        },
      },
      {
        'spotify': {
          'primary':          '#1db954',
          'primary-content':  '#000000',
          'secondary':        '#b3b3b3',
          'secondary-content':'#121212',
          'accent':           '#1ed760',
          'accent-content':   '#000000',
          'neutral':          '#282828',
          'neutral-content':  '#ffffff',
          'base-100':         '#121212',
          'base-200':         '#181818',
          'base-300':         '#282828',
          'base-content':     '#ffffff',
          'info':             '#0d72ea',
          'info-content':     '#ffffff',
          'success':          '#1db954',
          'success-content':  '#000000',
          'warning':          '#ffa42b',
          'warning-content':  '#000000',
          'error':            '#e91429',
          'error-content':    '#ffffff',
        },
      },
      {
        'netflix': {
          'primary':          '#e50914',
          'primary-content':  '#ffffff',
          'secondary':        '#b81d24',
          'secondary-content':'#ffffff',
          'accent':           '#e87c03',
          'accent-content':   '#ffffff',
          'neutral':          '#2f2f2f',
          'neutral-content':  '#ffffff',
          'base-100':         '#141414',
          'base-200':         '#1f1f1f',
          'base-300':         '#2f2f2f',
          'base-content':     '#ffffff',
          'info':             '#0080ff',
          'info-content':     '#ffffff',
          'success':          '#2bb24c',
          'success-content':  '#ffffff',
          'warning':          '#e87c03',
          'warning-content':  '#ffffff',
          'error':            '#e50914',
          'error-content':    '#ffffff',
        },
      },
      {
        'vscode': {
          'primary':          '#007acc',
          'primary-content':  '#ffffff',
          'secondary':        '#569cd6',
          'secondary-content':'#1e1e1e',
          'accent':           '#4ec9b0',
          'accent-content':   '#1e1e1e',
          'neutral':          '#3c3c3c',
          'neutral-content':  '#d4d4d4',
          'base-100':         '#1e1e1e',
          'base-200':         '#252526',
          'base-300':         '#333333',
          'base-content':     '#d4d4d4',
          'info':             '#007acc',
          'info-content':     '#ffffff',
          'success':          '#6a9955',
          'success-content':  '#ffffff',
          'warning':          '#ce9178',
          'warning-content':  '#1e1e1e',
          'error':            '#f44747',
          'error-content':    '#ffffff',
        },
      },
      {
        'notion-dark': {
          'primary':          '#ffffff',
          'primary-content':  '#191919',
          'secondary':        '#9b9b9b',
          'secondary-content':'#191919',
          'accent':           '#eb5757',
          'accent-content':   '#ffffff',
          'neutral':          '#2f2f2f',
          'neutral-content':  '#e8e8e8',
          'base-100':         '#191919',
          'base-200':         '#202020',
          'base-300':         '#2f2f2f',
          'base-content':     '#e8e8e8',
          'info':             '#0076d6',
          'info-content':     '#ffffff',
          'success':          '#0f7b6c',
          'success-content':  '#ffffff',
          'warning':          '#dfab01',
          'warning-content':  '#191919',
          'error':            '#eb5757',
          'error-content':    '#ffffff',
        },
      },
      {
        'twitter-x': {
          'primary':          '#1d9bf0',
          'primary-content':  '#ffffff',
          'secondary':        '#536471',
          'secondary-content':'#ffffff',
          'accent':           '#00ba7c',
          'accent-content':   '#000000',
          'neutral':          '#16181c',
          'neutral-content':  '#e7e9ea',
          'base-100':         '#000000',
          'base-200':         '#0d0d0d',
          'base-300':         '#16181c',
          'base-content':     '#e7e9ea',
          'info':             '#1d9bf0',
          'info-content':     '#ffffff',
          'success':          '#00ba7c',
          'success-content':  '#000000',
          'warning':          '#ffd400',
          'warning-content':  '#000000',
          'error':            '#f4212e',
          'error-content':    '#ffffff',
        },
      },
      {
        'supabase': {
          'primary':          '#3ecf8e',
          'primary-content':  '#1c1c1c',
          'secondary':        '#24b47e',
          'secondary-content':'#ffffff',
          'accent':           '#f59e0b',
          'accent-content':   '#1c1c1c',
          'neutral':          '#2a2a2a',
          'neutral-content':  '#e8e8e8',
          'base-100':         '#1c1c1c',
          'base-200':         '#242424',
          'base-300':         '#2e2e2e',
          'base-content':     '#e8e8e8',
          'info':             '#3ecf8e',
          'info-content':     '#1c1c1c',
          'success':          '#3ecf8e',
          'success-content':  '#1c1c1c',
          'warning':          '#f59e0b',
          'warning-content':  '#1c1c1c',
          'error':            '#ef4444',
          'error-content':    '#ffffff',
        },
      },
      {
        'linear': {
          'primary':          '#5e6ad2',
          'primary-content':  '#ffffff',
          'secondary':        '#4d55b8',
          'secondary-content':'#ffffff',
          'accent':           '#26c281',
          'accent-content':   '#ffffff',
          'neutral':          '#1e1e1e',
          'neutral-content':  '#d8d8d8',
          'base-100':         '#0f0f0f',
          'base-200':         '#161616',
          'base-300':         '#1e1e1e',
          'base-content':     '#d8d8d8',
          'info':             '#5e6ad2',
          'info-content':     '#ffffff',
          'success':          '#26c281',
          'success-content':  '#ffffff',
          'warning':          '#f2b024',
          'warning-content':  '#0f0f0f',
          'error':            '#e5484d',
          'error-content':    '#ffffff',
        },
      },
      {
        'figma-dark': {
          'primary':          '#18a0fb',
          'primary-content':  '#ffffff',
          'secondary':        '#9747ff',
          'secondary-content':'#ffffff',
          'accent':           '#0acf83',
          'accent-content':   '#ffffff',
          'neutral':          '#2c2c2c',
          'neutral-content':  '#e0e0e0',
          'base-100':         '#1e1e1e',
          'base-200':         '#2c2c2c',
          'base-300':         '#383838',
          'base-content':     '#e0e0e0',
          'info':             '#18a0fb',
          'info-content':     '#ffffff',
          'success':          '#0acf83',
          'success-content':  '#ffffff',
          'warning':          '#ffae1a',
          'warning-content':  '#1e1e1e',
          'error':            '#f24822',
          'error-content':    '#ffffff',
        },
      },
      // ── Retro themes ────────────────────────────────────────────────
      {
        'win95': {
          'primary':          '#000080',
          'primary-content':  '#ffffff',
          'secondary':        '#008080',
          'secondary-content':'#ffffff',
          'accent':           '#800000',
          'accent-content':   '#ffffff',
          'neutral':          '#808080',
          'neutral-content':  '#000000',
          'base-100':         '#c0c0c0',
          'base-200':         '#d4d0c8',
          'base-300':         '#a0a0a0',
          'base-content':     '#000000',
          'info':             '#000080',
          'info-content':     '#ffffff',
          'success':          '#008000',
          'success-content':  '#ffffff',
          'warning':          '#808000',
          'warning-content':  '#ffffff',
          'error':            '#800000',
          'error-content':    '#ffffff',
        },
      },
      {
        'winxp': {
          // Luna theme — ventanas beige, barra de título azul
          'primary':          '#1e56c8',
          'primary-content':  '#ffffff',
          'secondary':        '#3d8b37',
          'secondary-content':'#ffffff',
          'accent':           '#ff8c00',
          'accent-content':   '#ffffff',
          'neutral':          '#7b8b9a',
          'neutral-content':  '#ffffff',
          'base-100':         '#ece9d8',
          'base-200':         '#d4d0c8',
          'base-300':         '#aca899',
          'base-content':     '#000000',
          'info':             '#1e56c8',
          'info-content':     '#ffffff',
          'success':          '#3d8b37',
          'success-content':  '#ffffff',
          'warning':          '#ff8c00',
          'warning-content':  '#000000',
          'error':            '#cc0000',
          'error-content':    '#ffffff',
        },
      },
    ],
    darkTheme: 'dark',
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
};
