import { DragDropModule } from '@angular/cdk/drag-drop';
import { provideHttpClient } from '@angular/common/http';
import {
  ApplicationConfig,
  importProvidersFrom,
  provideZoneChangeDetection,
} from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { provideIcons } from '@ng-icons/core';
import {
  heroArrowDownTray,
  heroArrowLeft,
  heroArrowTurnDownRight,
  heroBars3,
  heroBolt,
  heroCalendarDays,
  heroChatBubbleBottomCenterText,
  heroCheckCircle,
  heroChevronDown,
  heroCog6Tooth,
  heroDocumentText,
  heroEye,
  heroEyeSlash,
  heroMagnifyingGlass,
  heroMusicalNote,
  heroPencil,
  heroPlus,
  heroPlusCircle,
  heroPrinter,
  heroQueueList,
  heroSignalSlash,
  heroStar,
  heroTrash,
  heroWrenchScrewdriver,
  heroXCircle,
  heroXMark,
} from '@ng-icons/heroicons/outline';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideHttpClient(),
    importProvidersFrom(BrowserAnimationsModule, DragDropModule),
    provideIcons({
      heroArrowDownTray,
      heroArrowLeft,
      heroArrowTurnDownRight,
      heroBars3,
      heroBolt,
      heroCalendarDays,
      heroChatBubbleBottomCenterText,
      heroCheckCircle,
      heroChevronDown,
      heroCog6Tooth,
      heroDocumentText,
      heroEye,
      heroEyeSlash,
      heroMagnifyingGlass,
      heroMusicalNote,
      heroPencil,
      heroPlus,
      heroPlusCircle,
      heroPrinter,
      heroQueueList,
      heroSignalSlash,
      heroStar,
      heroTrash,
      heroWrenchScrewdriver,
      heroXCircle,
      heroXMark,
    }),
  ],
};
