import { DragDropModule } from '@angular/cdk/drag-drop';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import {
  ApplicationConfig,
  importProvidersFrom,
  provideZoneChangeDetection,
} from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { provideIcons } from '@ng-icons/core';
import {
  heroArrowDownTray,
  heroArrowLeft,
  heroArrowPath,
  heroArrowRightOnRectangle,
  heroArrowTopRightOnSquare,
  heroArrowTurnDownRight,
  heroArrowUpTray,
  heroBars3,
  heroBolt,
  heroBuildingOffice2,
  heroCalendarDays,
  heroChatBubbleBottomCenterText,
  heroCheckCircle,
  heroChevronDown,
  heroChevronLeft,
  heroChevronRight,
  heroCog6Tooth,
  heroDocumentText,
  heroEnvelope,
  heroExclamationCircle,
  heroEye,
  heroEyeSlash,
  heroGlobeAlt,
  heroKey,
  heroLockClosed,
  heroMagnifyingGlass,
  heroMusicalNote,
  heroPencil,
  heroPlus,
  heroPhone,
  heroPlusCircle,
  heroPrinter,
  heroQueueList,
  heroSignalSlash,
  heroSparkles,
  heroStar,
  heroTrash,
  heroUser,
  heroUsers,
  heroWrenchScrewdriver,
  heroXCircle,
  heroXMark,
} from '@ng-icons/heroicons/outline';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideHttpClient(withInterceptors([authInterceptor])),
    importProvidersFrom(BrowserAnimationsModule, DragDropModule),
    provideIcons({
      heroArrowDownTray,
      heroArrowLeft,
      heroArrowPath,
      heroArrowRightOnRectangle,
      heroArrowTopRightOnSquare,
      heroArrowTurnDownRight,
      heroArrowUpTray,
      heroBars3,
      heroBolt,
      heroBuildingOffice2,
      heroCalendarDays,
      heroChatBubbleBottomCenterText,
      heroCheckCircle,
      heroChevronDown,
      heroChevronLeft,
      heroChevronRight,
      heroCog6Tooth,
      heroDocumentText,
      heroEnvelope,
      heroExclamationCircle,
      heroEye,
      heroEyeSlash,
      heroGlobeAlt,
      heroKey,
      heroLockClosed,
      heroMagnifyingGlass,
      heroMusicalNote,
      heroPencil,
      heroPlus,
      heroPhone,
      heroPlusCircle,
      heroPrinter,
      heroQueueList,
      heroSignalSlash,
      heroSparkles,
      heroStar,
      heroTrash,
      heroUser,
      heroUsers,
      heroWrenchScrewdriver,
      heroXCircle,
      heroXMark,
    }),
  ],
};
